### ISSUE TITLE
Can't install ggsvg package: "Fatal error: cannot open file '../tools/winlibs.R': No such file or directory"

### ISSUE THREAD

**Issue by mattbolanos** [coolbutuseless/ggsvg#5]
I'm having trouble installing this package on my Windows computer - I was able to install it on my Mac but am running into this error with trying to install it on Windows. I believe the issue may be related to RTools, however this is the only package I seem to have trouble installing (e.g. I was able to install ggrgl with no issues on both computers).

`remotes::install_github('coolbutuseless/ggsvg')
Downloading GitHub repo coolbutuseless/ggsvg@HEAD
√  checking for file 'C:\Users\mbolanos\AppData\Local\Temp\Rtmp217hyc\remotes4ac038db149a\coolbutuseless-ggsvg-dc3f523/DESCRIPTION' (381ms)
-  preparing 'ggsvg':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (631ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'ggsvg_0.1.3.tar.gz'
   
* installing *source* package 'ggsvg' ...
** using staged installation
** libs

*** arch - i386
rm -f ggsvg.dll init.o rsvg-utils.o
"C:/Users/mbolanos/DOCUME~1/R/R-41~1.3/bin/i386/Rscript.exe" "../tools/winlibs.R" 2.48.8
Fatal error: cannot open file '../tools/winlibs.R': No such file or directory

make: *** [Makevars.win:7: winlibs] Error 2
ERROR: compilation failed for package 'ggsvg'
* removing 'C:/Users/mbolanos/Documents/R/R-4.1.3/library/ggsvg'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/mbolanos/AppData/Local/Temp/Rtmp217hyc/file4ac01775522b/ggsvg_0.1.3.tar.gz’ had non-zero exit status`

Here is my System Path

Sys.getenv("PATH")
"C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Python\\Python310\\Scripts;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Python\\Python310;C:\\rtools40\\usr\\bin;C:\\Users\\mbolanos\\Documents\\R\\R-4.1.3\\bin\\x64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath_target_986375;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Python\\Python310\\Scripts;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Python\\Python310;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Python\\Launcher;C:\\Users\\mbolanos\\AppData\\Roaming\\TinyTeX\\bin\\win32;C:\\Users\\mbolanos\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64;C:\\Users\\mbolanos\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\RStudio\\bin\\rpostback;C:\\Program Files\\RStudio\\bin\\postback"

**Comment by coolbutuseless** [comment]
Please try a fresh install.  There was a rogue "Makevars.win" that I have removed from the code.  Let me know if that fixes it.

**Comment by mattbolanos** [comment]
Thank you that worked!
