### ISSUE TITLE
Not every observation is visible

### ISSUE THREAD

**Issue by unarsezer** [coolbutuseless/ggsvg#9]
Hi, I wanted to try the ggsvg package with the following codes:

svg_url <- 'https://www.svgrepo.com/download/289000/jellyfish.svg'
svg_txt <- paste(readLines(svg_url), collapse = "\n")

test_df <- data.frame(
  x = runif(10), 
  y = runif(10), 
  count = sample(3:5, 10, T),
  type  = sample(c('a', 'b', 'c'), 10, T))

ggplot(test_df) + 
  geom_point_svg(aes(x, y), svg = svg_txt, size = 10) + 
  theme_bw()

Interestingly, however, not every observation appears on the plot. Only 2 or 3 different observations appear every time I run the code.
![example](https://user-images.githubusercontent.com/65786664/184654599-2e622507-3bd8-4390-8c13-19881dd203a3.png)

**Comment by coolbutuseless** [comment]
A few questions:

Which version of ggsvg?
Which version of R?
Is this in Rstudio? 
What is your operating system?

**Comment by unarsezer** [comment]
Hi,
I am using 0.1.12 version of ggsvg.
R version is 4.1.1
Yes, this is in RStudio.
And I am using Windows 10.

When I add css("path", fill = "white") into the function, I can see every observation. For example,

ggplot(test_df) +
geom_point_svg(aes(x, y), svg = svg_txt, size = 10, css("path", fill = "white")) +
theme_bw()

the result is what it should be.

________________________________
Gönderen: mikefc ***@***.***>
Gönderildi: 15 Ağustos 2022 Pazartesi 23:24
Kime: coolbutuseless/ggsvg ***@***.***>
Bilgi: unarsezer ***@***.***>; Author ***@***.***>
Konu: Re: [coolbutuseless/ggsvg] Not every observation is visible (Issue #9)


A few questions:

Which version of ggsvg?
Which version of R?
Is this in Rstudio?
What is your operating system?

**Comment by coolbutuseless** [comment]
Thanks for reporting this.  I can't replicate this on my macOS machine, but I have some ideas on what might be happening on windows.  I will need your help!

Can you install the `issue09` test branch, run your "bad" plot again, and paste the output to the console as a reply to this issue?     

It would also be good to see the console output for the version of your plot that works i.e. when you set `css(path...)`

```remotes::install_github("coolbutuseless/ggsvg", ref = "issue09")```

**Comment by unarsezer** [comment]
Let's solve this problem together. 

I installed the issue09 with remotes::install_github("coolbutuseless/ggsvg", ref = "issue09")

This is the output of "bad" plot.
![ss1](https://user-images.githubusercontent.com/65786664/185633825-56a72557-0d0f-492e-8166-d6c9c57ef0fd.JPG)

And this is the output of css(path...) version.
![ss2](https://user-images.githubusercontent.com/65786664/185633934-64cf36e5-31b2-4a04-9175-e4c879bf4a30.JPG)

**Comment by coolbutuseless** [comment]
Both of those plots look correct to me now.

Has this fixed your issue?

If not, could you install the latest changes to the 'issue09' branch and try again?

**Comment by unarsezer** [comment]
Yes, everything is alright now, thanks 🙂
________________________________
Gönderen: mikefc ***@***.***>
Gönderildi: 20 Ağustos 2022 Cumartesi 02:50
Kime: coolbutuseless/ggsvg ***@***.***>
Bilgi: unarsezer ***@***.***>; Author ***@***.***>
Konu: Re: [coolbutuseless/ggsvg] Not every observation is visible (Issue #9)


Both of those plots look correct to me now.

Has this fixed your issue?
